title: Psi Beta Rho | UCLA
email: psibetarho@gmail.com
description: >-
  Psi Beta Rho is UCLA's competitive cybersecurity and CTF team! PBR is a part of ACM Cyber at UCLA.
baseurl: "/"
url: "https://pbr.uclaacm.com"
github: pbrucla
twitter: pbrucla
image: "assets/images/pbr-team-photo.jpeg"
permalink: /:categories/:year/:month/:day/:title

sass:
  sass_dir: assets/styles

kramdown:
  math_engine: katex

exclude:
- README.md
- .github/
