title: Buddurid's blog
email: bbahae624@gmail.com
description: >-
  this is a blog for my CTF's writeups  (mainly PWN) and maybe my future research papers .
baseurl: "/"
url: "https://buddurid.github.io"
github: buddurid
twitter: buddurid
image: "assets/images/luffy.jpg"
permalink: /:categories/:year/:month/:day/:title

sass:
  sass_dir: assets/styles

kramdown:
  math_engine: katex

exclude:
  - README.md
  - .github/
