title: Psi Beta Rho | UCLA
email: psibetarho@gmail.com
description: >-
  Psi Beta Rho is UCLA's competetive cybersecurity and CTF team! PBR is a part of ACM Cyber at UCLA.
baseurl: "/"
url: "https://pbr.uclaacm.com"
github: pbrucla
twitter: pbrucla

sass:
  sass_dir: assets/styles

exclude:
- README.md
- .github/