title: Psi Beta Rho | UCLA
email: psibetarho@gmail.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/"
url: "https://pbr.uclaacm.com"
github: pbrucla
twitter: pbrucla

sass:
  sass_dir: assets/styles

exclude:
- README.md
- .github/